server:
  port: 16005

grpc:
  server:
    port: 5555

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
  redis:
    host: localhost
    port: 6379
    database: 0

sms:
  activity-cancellation-template-id: 1732169
  activity-enrollment-template-id: 1732183
  sign-name: 米弥特
  sdk-app-id: 1400746566
  secret-key: 0sBIG5g6KK5f2MVZSCoPtHfu0ynSxMdj
  secret-id: AKIDxmdMtFRhuxulT8yjItFRQCoMhogPxOgn